language: node_js
node_js:
  - 12

services:
  - docker

# pre-testing installs
install:
  - echo "nothing nees to be installed"

before_script:
  - echo "no tests given"


script:
  - docker --version
  - docker build -t sammysium/api_user .
  - docker tag sammysium/api_user sammysium/api_user:latest

after_success:
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push sammysium/api_user