apiVersion: apps/v1
kind: Deployment
metadata:
  name: ud-ms-api-user
  labels:
    app: ud-ms-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ud-ms-api-user
  template:
    metadata:
      labels:
        app: ud-ms-api-user
    spec:
      containers:
      - name: api-user
        image: sammysium/api_user
      - alwaysPull: true
        ports:
        - containerPort: 8080
        env:
          - name: username
            value: semira
          - name: password
            value: semira503
          - name: database
            value: postgres
          - name: host
            value: udmsdb.crew3keyvyxp.us-east-2.rds.amazonaws.com
          - name: dialect
            value: postgres
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
