apiVersion: apps/v1
kind: Deployment
metadata:
  name: ud-ms-api-user
  labels:
    app: ud-ms-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ud-ms-api-user
  template:
    metadata:
      labels:
        app: ud-ms-api-user
    spec:
      containers:
      - name: api-user
        image: sammysium/api_user
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_HOST
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_PROFILE
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: AWS_BUCKET
          - name: URL
            value: localhost
          - name: JWT_SECRET
            value: secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
